command:
  - "streamlit"
  - "run"
  - "app.py"

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql_warehouse

resources:
  - name: sql_warehouse
    description: "Serverless Starter Warehouse used for all queries"
    sql_warehouse:
      id: 5a0ae21a29c598a3
      permission: CAN_USE
